%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\loic.vanel\Documents\Divers\Santé\Coronavirus\owid-covid-data.csv
%
% Auto-generated by MATLAB on 17-Aug-2020 12:52:59

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 40);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["iso_code", "continent", "location", "date1", "total_cases", "new_cases", "new_cases_smoothed", "total_deaths", "new_deaths", "new_deaths_smoothed", "total_cases_per_million", "new_cases_per_million", "new_cases_smoothed_per_million", "total_deaths_per_million", "new_deaths_per_million", "new_deaths_smoothed_per_million", "new_tests", "total_tests", "total_tests_per_thousand", "new_tests_per_thousand", "new_tests_smoothed", "new_tests_smoothed_per_thousand", "tests_per_case", "positive_rate", "tests_units", "stringency_index", "population", "population_density", "median_age", "aged_65_older", "aged_70_older", "gdp_per_capita", "extreme_poverty", "cardiovasc_death_rate", "diabetes_prevalence", "female_smokers", "male_smokers", "handwashing_facilities", "hospital_beds_per_thousand", "life_expectancy"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "string", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["new_tests", "total_tests", "total_tests_per_thousand", "new_tests_per_thousand", "new_tests_smoothed", "new_tests_smoothed_per_thousand", "tests_per_case", "positive_rate", "tests_units", "extreme_poverty", "female_smokers", "male_smokers"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["iso_code", "continent", "location", "new_tests", "total_tests", "total_tests_per_thousand", "new_tests_per_thousand", "new_tests_smoothed", "new_tests_smoothed_per_thousand", "tests_per_case", "positive_rate", "tests_units", "extreme_poverty", "female_smokers", "male_smokers"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date1", "InputFormat", "yyyy-MM-dd");

% Import the data
tbl = readtable("C:\Users\loic.vanel\Documents\Divers\Santé\Coronavirus\owid-covid-data.csv", opts);

%% Convert to output type
iso_code = tbl.iso_code;
continent = tbl.continent;
location = tbl.location;
date1 = tbl.date1;
total_cases = tbl.total_cases;
new_cases = tbl.new_cases;
new_cases_smoothed = tbl.new_cases_smoothed;
total_deaths = tbl.total_deaths;
new_deaths = tbl.new_deaths;
new_deaths_smoothed = tbl.new_deaths_smoothed;
total_cases_per_million = tbl.total_cases_per_million;
new_cases_per_million = tbl.new_cases_per_million;
new_cases_smoothed_per_million = tbl.new_cases_smoothed_per_million;
total_deaths_per_million = tbl.total_deaths_per_million;
new_deaths_per_million = tbl.new_deaths_per_million;
new_deaths_smoothed_per_million = tbl.new_deaths_smoothed_per_million;
new_tests = tbl.new_tests;
total_tests = tbl.total_tests;
total_tests_per_thousand = tbl.total_tests_per_thousand;
new_tests_per_thousand = tbl.new_tests_per_thousand;
new_tests_smoothed = tbl.new_tests_smoothed;
new_tests_smoothed_per_thousand = tbl.new_tests_smoothed_per_thousand;
tests_per_case = tbl.tests_per_case;
positive_rate = tbl.positive_rate;
tests_units = tbl.tests_units;
stringency_index = tbl.stringency_index;
population = tbl.population;
population_density = tbl.population_density;
median_age = tbl.median_age;
aged_65_older = tbl.aged_65_older;
aged_70_older = tbl.aged_70_older;
gdp_per_capita = tbl.gdp_per_capita;
extreme_poverty = tbl.extreme_poverty;
cardiovasc_death_rate = tbl.cardiovasc_death_rate;
diabetes_prevalence = tbl.diabetes_prevalence;
female_smokers = tbl.female_smokers;
male_smokers = tbl.male_smokers;
handwashing_facilities = tbl.handwashing_facilities;
hospital_beds_per_thousand = tbl.hospital_beds_per_thousand;
life_expectancy = tbl.life_expectancy;

%% Clear temporary variables
clear opts tbl